Document: kvp-server
Title: Debian kvp-server Manual
Author: <insert document author here>
Abstract: This manual describes what kvp-server is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kvp-server/kvp-server.sgml.gz

Format: postscript
Files: /usr/share/doc/kvp-server/kvp-server.ps.gz

Format: text
Files: /usr/share/doc/kvp-server/kvp-server.text.gz

Format: HTML
Index: /usr/share/doc/kvp-server/html/index.html
Files: /usr/share/doc/kvp-server/html/*.html
